### PR TITLE
Adds cart methods using 2D Arraylist

### PR DESCRIPTION
**Pull request by 22acmsu**
Adds newCart, clearCart, addCart, removeCart and changeCart initial implementations.

### CODE REVIEW

**Comment by noahpk2** [comment]
Looks great!

**Review by noahpk2 — APPROVED** [review]

**Review by mazzaccarom — APPROVED** [review]
repeating Noah's comment, "Looks Great"

**Comment by milagrosher11** [comment]
Looks great. Only error is the cart method but code will come into place.

**Comment by 22acmsu** [comment]
Oh I see the errors you mentioned, thanks for fixing them in the followup method.

**Pull request merged**
