### PR TITLE
ProfitBetweenDates class/fixed OverallProfit bugs

### PR DESCRIPTION
**Pull request by tluke3**
Created ProfitBetweenDates class to find the profit between two dates (formatted MM/dd/yyyy) and fixed bugs with OverallProfit class

### CODE REVIEW

**Review by milagrosher11 — COMMENTED** [review]
Can't approve just yet because I'm, seeing some errors on lines 19,22-24. Check your code again. Probably have some basic errors.

**Comment by tluke3** [comment]
I'm not seeing any errors on my side.

**Review by milagrosher11 — APPROVED** [review]
Tried again and VSC is showing me no errors. Everything is working fine.

**Review by milagrosher11 — APPROVED** [review]

**Comment by noahpk2** [comment]
Looks good! lets definitely get all these features fully implemented for the last sprint

**Review by noahpk2 — COMMENTED** [review]
looks great

**Pull request merged**
